### PR TITLE
Bug Fix for SingleCellMemap Concat Function 

### PR DESCRIPTION
**Pull request by savitha-eng**
## Summary
This PR contains a bug fix for the row index creation in the `concat` function of the SingleCellMemap Dataset. This bug occurs in the use case when a user is collating multiple h5ad files into a SingleCellMemmap dataset via a SingleCellCollection/the flatten function. 

## Details
Previously, the `concat` function was initializing the number of elements in the cumulative row index incorrectly for more than one dataset since it was incrementing the cumulative elements using the number of rows rather than the number of non zero elements thus far. This resulted in cases where the row index was no longer accurate (and no longer monotonically increasing), and thus the gene data retrieved by using these row pointers via functions like scmemmap.get_row was incorrect. 

## Usage
There are no changes to how the user interacts with the changed code. 

## Testing
We add a regression unit test for the specific case on the val data that was failing previously. 
Tests for these changes can be run via:
```shell
pytest -v /workspace/bionemo2/sub-packages/bionemo-scdl/tests/bionemo/scdl/io/test_single_cell_collection.py::test_sc_concat_in_flatten_cellxval

```

- [ ] Did you review the [Before your PR is "Ready for review" section](https://github.com/NVIDIA/bionemo-framework/-/blob/dev/CONTRIBUTING.md?ref_type=heads#before-pr-ready) before asking for review?
- [ ] Did you make sure your changes have tests? Did you test your changes locally?
- [ ] Can you add [the `SKIP_CI` label](https://github.com/NVIDIA/bionemo-framework/-/blob/dev/CONTRIBUTING.md?ref_type=heads#skip-ci) to your PR?
- [ ] Can you add [the `PYTEST_NOT_REQUIRED` label](https://github.com/NVIDIA/bionemo-framework/-/blob/dev/CONTRIBUTING.md?ref_type=heads#skip-pytest) to your PR?
- [ ] Can you add [the `JET_NOT_REQUIRED` label](https://github.com/NVIDIA/bionemo-framework/-/blob/dev/CONTRIBUTING.md?ref_type=heads#skip-jet) to your PR?

### CODE REVIEW

**Review by malcolmgreaves — APPROVED** [review]
Great PR commit message, nice fix, and great tests! 👏 LGTM

**Review by polinabinder1 — APPROVED** [review]

**Pull request merged**
